version: "2"
services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - back
  back:
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
